pokemon_data = [
    ["0001", "Bisasam", "Bulbasaur", "フシギダネ", "이상해씨", "妙蛙種子 / 妙蛙种子", "Pflanze Gift"],
    ["0002", "Bisaknosp", "Ivysaur", "フシギソウ", "이상해풀", "妙蛙草 / 妙蛙草", "Pflanze Gift"],
    ["0003", "Bisaflor", "Venusaur", "フシギバナ", "이상해꽃", "妙蛙花 / 妙蛙花", "Pflanze Gift"],
    ["0004", "Glumanda", "Charmander", "ヒトカゲ", "파이리", "小火龍 / 小火龙", "Feuer"],
    ["0005", "Glutexo", "Charmeleon", "リザード", "리자드", "火恐龍 / 火恐龙", "Feuer"],
    ["0006", "Glurak", "Charizard", "リザードン", "리자몽", "噴火龍 / 喷火龙", "Feuer Flug"],
    ["0007", "Schiggy", "Squirtle", "ゼニガメ", "꼬부기", "傑尼龜 / 杰尼龟", "Wasser"],
    ["0008", "Schillok", "Wartortle", "カメール", "어니부기", "卡咪龜 / 卡咪龟", "Wasser"],
    ["0009", "Turtok", "Blastoise", "カメックス", "거북왕", "水箭龜 / 水箭龟", "Wasser"],
    ["0010", "Raupy", "Caterpie", "キャタピー", "캐터피", "綠毛蟲 / 绿毛虫", "Käfer"],
    ["0011", "Safcon", "Metapod", "トランセル", "단데기", "鐵甲蛹 / 铁甲蛹", "Käfer"],
    ["0012", "Smettbo", "Butterfree", "バタフリー", "버터플", "巴大蝶 / 巴大蝶", "Käfer Flug"],
    ["0013", "Hornliu", "Weedle", "ビードル", "뿔충이", "獨角蟲 / 独角虫", "Käfer Gift"],
    ["0014", "Kokuna", "Kakuna", "コクーン", "딱충이", "鐵殼蛹 / 铁壳蛹", "Käfer Gift"],
    ["0015", "Bibor", "Beedrill", "スピアー", "독침붕", "大針蜂 / 大针蜂", "Käfer Gift"],
    ["0016", "Taubsi", "Pidgey", "ポッポ", "구구", "波波 / 波波", "Normal Flug"],
    ["0017", "Tauboga", "Pidgeotto", "ピジョン", "피죤", "比比鳥 / 比比鸟", "Normal Flug"],
    ["0018", "Tauboss", "Pidgeot", "ピジョット", "피죤투", "大比鳥 / 大比鸟", "Normal Flug"],
    ["0019", "Rattfratz", "Rattata", "コラッタ", "꼬렛", "小拉達 / 小拉达", "Normal"],
    ["0020", "Rattikarl", "Raticate", "ラッタ", "레트라", "拉達 / 拉达", "Normal"],
    ["0021", "Habitak", "Spearow", "オニスズメ", "깨비참", "烈雀 / 烈雀", "Normal Flug"],
    ["0022", "Ibitak", "Fearow", "オニドリル", "깨비드릴조", "大嘴雀 / 大嘴雀", "Normal Flug"],
    ["0023", "Rettan", "Ekans", "アーボ", "아보", "阿柏蛇 / 阿柏蛇", "Gift"],
    ["0024", "Arbok", "Arbok", "アーボック", "아보크", "阿柏怪 / 阿柏怪", "Gift"],
    ["0025", "Pikachu", "Pikachu", "ピカチュウ", "피카츄", "皮卡丘 / 皮卡丘", "Elektro"],
    ["0026", "Raichu", "Raichu", "ライチュウ", "라이츄", "雷丘 / 雷丘", "Elektro"],
    ["0027", "Sandan", "Sandshrew", "サンド", "모래두지", "穿山鼠 / 穿山鼠", "Boden"],
    ["0028", "Sandamer", "Sandslash", "サンドパン", "고지", "穿山王 / 穿山王", "Boden"],
    ["0029", "Nidoran♀", "Nidoran♀", "ニドラン♀", "니드런♀", "尼多蘭 / 尼多兰", "Gift"],
    ["0030", "Nidorina", "Nidorina", "ニドリーナ", "니드리나", "尼多娜 / 尼多娜", "Gift"],
    ["0031", "Nidoqueen", "Nidoqueen", "ニドクイン", "니드퀸", "尼多后 / 尼多后", "Gift Boden"],
    ["0032", "Nidoran♂", "Nidoran♂", "ニドラン♂", "니드런♂", "尼多朗 / 尼多朗", "Gift"],
    ["0033", "Nidorino", "Nidorino", "ニドリーノ", "니드리노", "尼多力諾 / 尼多力诺", "Gift"],
    ["0034", "Nidoking", "Nidoking", "ニドキング", "니드킹", "尼多王 / 尼多王", "Gift Boden"],
    ["0035", "Piepi", "Clefairy", "ピッピ", "삐삐", "皮皮 / 皮皮", "Fee"],
    ["0036", "Pixi", "Clefable", "ピクシー", "픽시", "皮可西 / 皮可西", "Fee"],
    ["0037", "Vulpix", "Vulpix", "ロコン", "식스테일", "六尾 / 六尾", "Feuer"],
    ["0038", "Vulnona", "Ninetales", "キュウコン", "나인테일", "九尾 / 九尾", "Feuer"],
    ["0039", "Pummeluff", "Jigglypuff", "プリン", "푸린", "胖丁 / 胖丁", "Normal Fee"],
    ["0040", "Knuddeluff", "Wigglytuff", "プクリン", "푸크린", "胖可丁 / 胖可丁", "Normal Fee"],
    ["0041", "Zubat", "Zubat", "ズバット", "주뱃", "超音蝠 / 超音蝠", "Gift Flug"],
    ["0042", "Golbat", "Golbat", "ゴルバット", "골뱃", "大嘴蝠 / 大嘴蝠", "Gift Flug"],
    ["0043", "Myrapla", "Oddish", "ナゾノクサ", "뚜벅쵸", "走路草 / 走路草", "Pflanze Gift"],
    ["0044", "Duflor", "Gloom", "クサイハナ", "냄새꼬", "臭臭花 / 臭臭花", "Pflanze Gift"],
    ["0045", "Giflor", "Vileplume", "ラフレシア", "라플레시아", "霸王花 / 霸王花", "Pflanze Gift"],
    ["0046", "Paras", "Paras", "パラス", "파라스", "派拉斯 / 派拉斯", "Käfer Pflanze"],
    ["0047", "Parasek", "Parasect", "パラセクト", "파라섹트", "派拉斯特 / 派拉斯特", "Käfer Pflanze"],
    ["0048", "Bluzuk", "Venonat", "コンパン", "콘팡", "毛球 / 毛球", "Käfer Gift"],
    ["0049", "Omot", "Venomoth", "モルフォン", "도나리", "末入蛾 / 末入蛾", "Käfer Gift"],
    ["0050", "Digda", "Diglett", "ディグダ", "디그다", "地鼠 / 地鼠", "Boden"],
    ["0051", "Digdri", "Dugtrio", "ダグトリオ", "닥트리오", "三地鼠 / 三地鼠", "Boden"],
    ["0052", "Mauzi", "Meowth", "ニャース", "나옹", "喵喵 / 喵喵", "Normal"],
    ["0053", "Snobilikat", "Persian", "ペルシアン", "페르시온", "貓老大 / 猫老大", "Normal"],
    ["0054", "Enton", "Psyduck", "Psykokwak", "コダックKoduck", "고라파덕Gorapaduck", "可達鴨 / 可达鸭Kědáyā", "Wasser"],
    ["0055", "Entoron", "Golduck", "Akwakwak", "ゴルダックGolduck", "골덕Golduck", "哥達鴨 / 哥达鸭Gēdáyā", "Wasser"],
    ["0056", "Menki", "Mankey", "Férosinge", "マンキーMankey", "망키Mankey", "猴怪 / 猴怪Hóuguài", "Kampf"],
    ["0057", "Rasaff", "Primeape", "Colossinge", "オコリザルOkorizaru", "성원숭Seongwonsung", "火爆猴 / 火爆猴Huǒbàohóu", "Kampf"],
    ["0058", "Fukano", "Growlithe", "Caninos", "ガーディGardie", "가디Gadi", "卡蒂狗 / 卡蒂狗Kǎdìgǒu", "Feuer"],
    ["0059", "Arkani", "Arcanine", "Arcanin", "ウインディWindie", "윈디Windi", "風速狗 / 风速狗Fēngsùgǒu", "Feuer"],
    ["0060", "Quapsel", "Poliwag", "Ptitard", "ニョロモNyoromo", "발챙이Balchengi", "蚊香蝌蚪 / 蚊香蝌蚪Wénxiāngkēdǒu", "Wasser"],
    ["0061", "Quaputzi", "Poliwhirl", "Têtarte", "ニョロゾNyorozo", "슈륙챙이Shuryukchengi", "蚊香君 / 蚊香君Wénxiāngjūn", "Wasser"],
    ["0062", "Quappo", "Poliwrath", "Tartard", "ニョロボンNyorobon", "강챙이Gangchaengi", "蚊香泳士 / 蚊香泳士Wénxiāngyǒngshì", "Wasser Kampf"],
    ["0063", "Abra", "Abra", "Abra", "ケーシィCasey", "캐이시Keisi", "凱西 / 凯西Kǎixī", "Psycho"],
    ["0064", "Kadabra", "Kadabra", "Kadabra", "ユンゲラーYungerer", "윤겔라Yunghelar", "勇基拉 / 勇基拉Yǒngjīlā", "Psycho"],
    ["0065", "Simsala", "Alakazam", "Alakazam", "フーディンFoodin", "후딘Fudin", "胡地 / 胡地Húdì", "Psycho"],
    ["0066", "Machollo", "Machop", "Machoc", "ワンリキーWanriky", "알통몬Altongmon", "腕力 / 腕力Wànlì", "Kampf"],
    ["0067", "Maschock", "Machoke", "Machopeur", "ゴーリキーGoriky", "근육몬Geunyukmon", "豪力 / 豪力Háolì", "Kampf"],
    ["0068", "Machomei", "Machamp", "Mackogneur", "カイリキーKairiky", "괴력몬Goeryeokmon", "怪力 / 怪力Guàilì", "Kampf"],
    ["0069", "Knofensa", "Bellsprout", "Chétiflor", "マダツボミMadatsubomi", "모다피Modapi", "喇叭芽 / 喇叭芽Lǎbāyá", "Pflanze Gift"],
    ["0070", "Ultrigaria", "Weepinbell", "Boustiflor", "ウツドンUtsudon", "우츠동Uchudon", "口呆花 / 口呆花Kǒudāihuā", "Pflanze Gift"],
    ["0071", "Sarzenia", "Victreebel", "Empiflor", "ウツボットUtsubot", "우츠보트Uchubot", "大食花 / 大食花Dàshíhuā", "Pflanze Gift"],
    ["0072", "Tentacha", "Tentacool", "Tentacool", "メノクラゲMenokurage", "왕눈해Wangnunhe", "瑪瑙水母 / 玛瑙水母Mǎnǎoshuǐmǔ", "Wasser Gift"],
    ["0073", "Tentoxa", "Tentacruel", "Tentacruel", "ドククラゲDokukurage", "독파리Tokpari", "毒刺水母 / 毒刺水母Dúcìshuǐmǔ", "Wasser Gift"],
    ["0074", "Kleinstein", "Geodude", "Racaillou", "イシツブテIsitsubute", "꼬마돌Kkomadol", "小拳石 / 小拳石Xiǎoquánshí", "Gestein Boden"],
    ["0075", "Georok", "Graveler", "Gravalanch", "ゴローンGolone", "데구리Deguri", "隆隆石 / 隆隆石Lónglóngshí", "Gestein Boden"],
    ["0076", "Geowaz", "Golem", "Grolem", "ゴローニャGoronya", "딱구리Ddakguri", "隆隆岩 / 隆隆岩Lónglóngyán", "Gestein Boden"],
    ["0077", "Ponita", "Ponyta", "Ponita", "ポニータPonita", "포니타Ponita", "小火馬 / 小火马Xiǎohuǒmǎ", "Feuer"],
    ["0078", "Gallopa", "Rapidash", "Galopa", "ギャロップGyaroppu", "날쌩마Nalssaengma", "烈焰馬 / 烈焰马Lièyàn mǎ", "Feuer"],
    ["0079", "Flegmon", "Slowpoke", "Ramoloss", "ヤドンYadon", "야돈Yadon", "呆呆獸 / 呆呆兽Dāidāishòu", "Wasser Psycho"],
    ["0080", "Lahmus", "Slowbro", "Flagadoss", "ヤドランYadoran", "야도란Yadoran", "呆河馬 / 呆河马Dāihémǎ", "Wasser Psycho"],
    ["0081", "Magnetilo", "Magnemite", "Magnéti", "コイルKoiru", "코일Koil", "小磁怪 / 小磁怪Xiǎocígúai", "Elektro Stahl"],
    ["0082", "Magneton", "Magneton", "Magnéton", "レアコイルReakoiru", "레어코일Rekokoil", "三合一磁怪 / 三合一磁怪Sānhéyīcígúai", "Elektro Stahl"],
    ["0083", "Porenta", "Farfetch'd", "Canarticho", "カモネギKamonegi", "파오리Paori", "大葱鴨 / 大葱鸭Dàcōngyā", "Normal Flug"],
    ["0084", "Dodu", "Doduo", "Doduo", "ドードーDodo", "두두Dudu", "嘟嘟 / 嘟嘟Dūdū", "Normal Flug"],
    ["0085", "Dodri", "Dodrio", "Dodrio", "ドードリオDodorio", "두트리Dutri", "嘟嘟利 / 嘟嘟利Dūdūlì", "Normal Flug"],
    ["0086", "Jurob", "Seel", "Otaria", "パウワウPauwau", "쥬쥬Jyujyu", "小海獅 / 小海狮Xiǎohǎishī", "Wasser"],
    ["0087", "Jugong", "Dewgong", "Lamantine", "ジュゴンJugon", "쥬레곤Jyuregon", "白海獅 / 白海狮Báihǎishī", "Wasser Eis"],
    ["0088", "Sleima", "Grimer", "Tadmorv", "ベトベターBetobeta", "질퍽이Jilpogi", "臭泥 / 臭泥Chòuní", "Gift"],
    ["0089", "Sleimok", "Muk", "Grotadmorv", "ベトベトンBetbeton", "질뻐기Jilppeogi", "臭臭泥 / 臭臭泥Chòuchòuní", "Gift"],
    ["0090", "Muschas", "Shellder", "Kokiyas", "シェルダーSherudā", "셀러Shellder", "大舌貝 / 大舌贝Dàshékè", "Wasser"],
    ["0091", "Austos", "Cloyster", "Crustabri", "パルシェンParshen", "파르셀Parshel", "刺甲貝 / 刺甲贝Cìjiǎbèi", "Wasser Eis"],
    ["0092", "Nebulak", "Gastly", "Fantominus", "ゴースGōsu", "고오스Gooseu", "鬼斯 / 鬼斯Guǐsī", "Geist Gift"],
    ["0093", "Alpollo", "Haunter", "Spectrum", "ゴーストGōsuto", "고우스트Gousteu", "幽靈 / 幽灵Yōulíng", "Geist Gift"],
    ["0094", "Gengar", "Gengar", "Ectoplasma", "ゲンガーGengā", "팬텀Phantom", "耿鬼 / 耿鬼Gěngguǐ", "Geist Gift"],
    ["0095", "Onix", "Onix", "Onix", "イワークIwāku", "롱스롱스Longseulongseu", "大岩蛇 / 大岩蛇Dà yán shé", "Gestein Boden"],
    ["0096", "Traumato", "Drowzee", "Soporifik", "スリープSurīpu", "슬리프Seullipeu", "食夢獸 / 食梦兽Shímèngshòu", "Psycho"],
    ["0097", "Hypno", "Hypno", "Hypnomade", "スリーパーSurīpā", "슬리퍼Seullipeo", "夢夢貘 / 梦梦貘Mèngmèngmò", "Psycho"],
    ["0098", "Krabby", "Krabby", "Krabby", "クラブCrab", "크랩Kreb", "大鉗蟹 / 大钳蟹Dàqiánxiè", "Wasser"],
    ["0099", "Kingler", "Kingler", "Krabboss", "キングラーKingler", "킹크랩Kingkreb", "巨鉗蟹 / 巨钳蟹Jùqiánxiè", "Wasser"],
    ["0100", "Voltobal", "Voltorb", "Voltorbe", "ビリリダマBiriridama", "찌리리공Zzililigong", "霹靂電球 / 霹雳电球Pīlìdiànqiú", "Elektro"],
    ["0101", "Lektrobal", "Electrode", "Électrode", "マルマインMarumine", "붐볼Boomball", "頑皮雷彈 / 顽皮雷弹Wánpíléidàn", "Elektro"],
    ["0102", "Owei", "Exeggcute", "Noeunoeuf", "タマタマTamatama", "아라리Arari", "蛋蛋 / 蛋蛋Dàndàn", "Pflanze Psycho"],
    ["0103", "Kokowei", "Exeggutor", "Noadkoko", "ナッシーNassy", "나시Nasi", "椰蛋樹 / 椰蛋树Yēdànshù", "Pflanze Psycho"],
    ["0104", "Tragosso", "Cubone", "Osselait", "カラカラKarakara", "탕구리Tangguri", "卡拉卡拉 / 卡拉卡拉Kǎlākǎlā", "Boden"],
    ["0105", "Knogga", "Marowak", "Ossatueur", "ガラガラGaragara", "텅구리Teongguri", "嘎啦嘎啦 / 嘎啦嘎啦Gālāgālā", "Boden"],
    ["0106", "Kicklee", "Hitmonlee", "Kicklee", "サワムラーSawamular", "시라소몬Sirasomon", "飛腿郎 / 飞腿郎Fēituǐláng", "Kampf"],
    ["0107", "Nockchan", "Hitmonchan", "Tygnon", "エビワラーEbiwalar", "홍수몬Hongsoomon", "快拳郎 / 快拳郎Kuàiquánláng", "Kampf"],
    ["0108", "Schlurp", "Lickitung", "Excelangue", "ベロリンガBeroringa", "내루미Nerumi", "大舌頭 / 大舌头Dàshétóu", "Normal"],
    ["0109", "Smogon", "Koffing", "Smogo", "ドガースDogars", "또가스Ttogas", "瓦斯彈 / 瓦斯弹Wǎsīdàn", "Gift"],
    ["0110", "Smogmog", "Weezing", "Smogogo", "マタドガスMatadogas", "또도가스Ttodogas", "雙彈瓦斯 / 双弹瓦斯Shuāngdànwǎsī", "Gift"],
    ["0111", "Rihorn", "Rhyhorn", "Rhinocorne", "サイホーンSihorn", "뿔카노Ppulkano", "獨角犀牛 / 独角犀牛Dújiǎoxīniú", "Boden Gestein"],
    ["0112", "Rizeros", "Rhydon", "Rhinoféros", "サイドンSidon", "코뿌리Koppuri", "鑽角犀獸 / 钻角犀兽Zuānjiǎoxīshòu", "Boden Gestein"],
    ["0113", "Chaneira", "Chansey", "Leveinard", "ラッキーLucky", "럭키Lucki", "吉利蛋 / 吉利蛋Jílìdàn", "Normal"],
    ["0114", "Tangela", "Tangela", "Saquedeneu", "モンジャラMonjara", "덩쿠리Deongkuri", "蔓藤怪 / 蔓藤怪Mànténgguài", "Pflanze"],
    ["0115", "Kangama", "Kangaskhan", "Kangourex", "ガルーラGarura", "캥카Kengka", "袋獸 / 袋兽Dàishòu", "Normal"],
    ["0116", "Seeper", "Horsea", "Hypotrempe", "タッツーTattu", "쏘드라Ssodra", "墨海馬 / 墨海马Mòhǎimǎ", "Wasser"],
    ["0117", "Seemon", "Seadra", "Hypocéan", "シードラSeadra", "시드라Seadra", "海刺龍 / 海刺龙Hǎicìlóng", "Wasser"],
    ["0118", "Goldini", "Goldeen", "Poissirène", "トサキントTosakinto", "콘치Konchi", "角金魚 / 角金鱼Jiǎojīnyú", "Wasser"],
    ["0119", "Golking", "Seaking", "Poissoroy", "アズマオウAzumao", "왕콘치Wangkonchi", "金魚王 / 金鱼王Jīnyúwáng", "Wasser"],
    ["0120", "Sterndu", "Staryu", "Stari", "ヒトデマンHitodeman", "별가사리Byulgasari", "海星星 / 海星星Hǎixīngxīng", "Wasser"],
    ["0121", "Starmie", "Starmie", "Staross", "スターミーStarmie", "아쿠스타Akusta", "寶石海星 / 宝石海星Bǎoshíhǎixīng", "Wasser Psycho"],
    ["0122", "Pantimos", "Mr. Mime", "M. Mime", "バリヤードBarrierd", "마임맨Maimman", "魔牆人偶 / 魔墙人偶Móqiángrén'ǒu", "Psycho Fee"],
    ["0123", "Sichlor", "Scyther", "Insécateur", "ストライクStrike", "스라크Srak", "飛天螳螂 / 飞天螳螂Fēitiāntángláng", "Käfer Flug"],
    ["0124", "Rossana", "Jynx", "Lippoutou", "ルージュラRougela", "루주라Rujura", "迷唇姐 / 迷唇姐Míchúnjiě", "Eis Psycho"],
    ["0125", "Elektek", "Electabuzz", "Élektek", "エレブーEleboo", "에레브Elev", "電擊獸 / 电击兽Diànjīshòu", "Elektro"],
    ["0126", "Magmar", "Magmar", "Magmar", "ブーバーBoober", "마그마Magmar", "鴨嘴火獸 / 鸭嘴火兽Yāzuǐhuǒshòu", "Feuer"],
    ["0127", "Pinsir", "Pinsir", "Scarabrute", "カイロスKailios", "쁘사이저Ppeusaizeo", "凱羅斯 / 凯罗斯Kǎiluósī", "Käfer"],
    ["0128", "Tauros", "Tauros", "Tauros", "ケンタロスKentauros", "켄타로스Kentaros", "肯泰羅 / 肯泰罗Kěntàiluó", "Normal"],
    ["0129", "Karpador", "Magikarp", "Magicarpe", "コイキングKoiking", "잉어킹Ingeoking", "鯉魚王 / 鲤鱼王Lǐyúwáng", "Wasser"],
    ["0130", "Garados", "Gyarados", "Léviator", "ギャラドスGyarados", "갸라도스Gyarados", "暴鯉龍 / 暴鲤龙Bàolǐlóng", "Wasser Flug"],
    ["0131", "Lapras", "Lapras", "Lokhlass", "ラプラスLaplace", "라프라스Lapras", "拉普拉斯 / 拉普拉斯Lāpǔlāsī", "Wasser Eis"],
    ["0132", "Ditto", "Ditto", "Métamorph", "メタモンMetamon", "메타몽Metamong", "百變怪 / 百变怪Bǎibiànguài", "Normal"],
    ["0133", "Evoli", "Eevee", "Évoli", "イーブイEievui", "이브이Eevee", "伊布 / 伊布Yībù", "Normal"],
    ["0134", "Aquana", "Vaporeon", "Aquali", "シャワーズShowers", "샤미드Shamid", "水伊布 / 水伊布Shuǐyībù", "Wasser"],
    ["0135", "Blitza", "Jolteon", "Voltali", "サンダースThunders", "쥬피썬더Jupithunder", "雷伊布 / 雷伊布Léiyībù", "Elektro"],
    ["0136", "Flamara", "Flareon", "Pyroli", "ブースターBooster", "부스터Booster", "火伊布 / 火伊布Huǒyībù", "Feuer"],
    ["0137", "Porygon", "Porygon", "Porygon", "ポリゴンPorygon", "폴리곤Porygon", "多邊獸 / 多边兽Duōbiānshòu", "Normal"],
    ["0138", "Amonitas", "Omanyte", "Amonita", "オムナイトOmnite", "암나이트Amnait", "菊石獸 / 菊石兽Júshíshòu", "Gestein Wasser"],
    ["0139", "Amoroso", "Omastar", "Amonistar", "オムスターOmstar", "암스타Amsta", "多刺菊石獸 / 多刺菊石兽Duōcìjúshíshòu", "Gestein Wasser"],
    ["0140", "Kabuto", "Kabuto", "Kabuto", "カブトKabuto", "투구Toogu", "化石盔 / 化石盔Huàshíkuī", "Gestein Wasser"],
    ["0141", "Kabutops", "Kabutops", "Kabutops", "カブトプスKabutops", "투구푸스Tooguphus", "鐮刀盔 / 镰刀盔Liándāokuī", "Gestein Wasser"],
    ["0142", "Aerodactyl", "Aerodactyl", "Ptéra", "プテラPtera", "프테라Ptera", "化石翼龍 / 化石翼龙Huàshíyìlóng", "Gestein Flug"],
    ["0143", "Relaxo", "Snorlax", "Ronflex", "カビゴンKabigon", "잠만보Jammanbo", "卡比獸 / 卡比兽Kǎbǐshòu", "Normal"],
    ["0144", "Arktos", "Articuno", "Artikodin", "フリーザーFreezer", "프리져Freeser", "急凍鳥 / 急冻鸟Jídòngniǎo", "Eis Flug"],
    ["0145", "Zapdos", "Zapdos", "Électhor", "サンダーThunder", "썬더Sunder", "閃電鳥 / 闪电鸟Shǎndiànniǎo", "Elektro Flug"],
    ["0146", "Lavados", "Moltres", "Sulfura", "ファイヤーFire", "파이어Faier", "火焰鳥 / 火焰鸟Huǒyànniǎo", "Feuer Flug"],
    ["0147", "Dratini", "Dratini", "Minidraco", "ミニリュウMiniryu", "미뇽Minyong", "迷你龍 / 迷你龙Mínǐlóng", "Drache"],
    ["0148", "Dragonir", "Dragonair", "Draco", "ハクリューHakuryu", "신뇽Sinnyong", "哈克龍 / 哈克龙Hākèlóng", "Drache"],
    ["0149", "Dragoran", "Dragonite", "Dracolosse", "カイリューKairyu", "망나뇽Mangnanyong", "快龍 / 快龙Kuàilóng", "Drache Flug"],
    ["0150", "Mewtu", "Mewtwo", "Mewtwo", "ミュウツーMewtwo", "뮤츠Mewtwo", "超夢 / 超梦Chāomèng", "Psycho"],
    ["0151", "Mew", "Mew", "Mew", "ミュウMew", "뮤Mew", "夢幻 / 梦幻Mènghuàn", "Psycho"]
];